### ISSUE TITLE
[Feature]After using css to set the text to be non-selectable, calling the pdf method will make the printed pdf text non-selectable.

### ISSUE THREAD

**Issue by lin-mt** [microsoft/playwright-java#1373]
My css style：

```css
.noselect {
    -webkit-touch-callout: none;
    -webkit-user-select: none;
    -khtml-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
}
```

My dom:
```html
<p>
  Selectable text.
</p>
<p class="noselect">
  Unselectable text.
</p>
```

After generating a PDF file, the `Unselectable text.` of the file content is still selectable. I hope that the non-selectable html elements are still not selectable in the pdf file when the pdf is generated. Perhaps this kind of html element is more suitable for displaying in the pdf as a image.
