### ISSUE TITLE
[REGRESSION]: Performing tests on Selenium Grid 4 

### ISSUE THREAD

**Issue by darek31978** [microsoft/playwright-java#798]
**Context:**
- GOOD Playwright Version: 1.17.2
- BAD Playwright Version: 1.18.0
- Operating System: Linux

**Code Snippet**

```java
    @BeforeAll
    void launchBrowser() {
        launchOptions.setHeadless(true);
        launchOptions.setChromiumSandbox(false);
        launchOptions.setChannel("chrome");
        args.add("--ipc=host");
        args.add("--disable-dev-shm-usage");
        args.add("--whitelisted-ips");
        launchOptions.setArgs(args);

        playwright = Playwright.create();

        browser = playwright.chromium().launch(launchOptions);

    }
```
docker-compose.yml creating a selenium grid 
```yml
version: "3"
services:
  chrome:
    image: selenium/node-chrome:4.1.1-20220121
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=4
      - VNC_NO_PASSWORD=1
  
  selenium-hub:
    image: selenium/hub:4.1.1-20220121
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

```
test execution command
```
SELENIUM_REMOTE_URL=http://192.168.0.144:4444/wd/hub mvn clean test
```
**Describe the bug**

Running tests on Selenium Grid 4 for Playwright 1.17.2 works fine, after upgrading to 1.18.0 I get:
```
selenium-hub    | 10:31:45.702 INFO [LocalDistributor.newSession] - Session request received by the distributor: 
selenium-hub    |  [Capabilities {browserName: chrome, goog:chromeOptions: {args: [--disable-background-networ..., --enable-features=NetworkSe..., --disable-background-timer-..., --disable-backgrounding-occ..., --disable-breakpad, --disable-client-side-phish..., --disable-component-extensi..., --disable-default-apps, --disable-dev-shm-usage, --disable-extensions, --disable-features=Improved..., --allow-pre-commit-input, --disable-hang-monitor, --disable-ipc-flooding-prot..., --disable-popup-blocking, --disable-prompt-on-repost, --disable-renderer-backgrou..., --disable-sync, --force-color-profile=srgb, --metrics-recording-only, --no-first-run, --enable-automation, --password-store=basic, --use-mock-keychain, --no-service-autorun, --export-tagged-pdf, --headless, --hide-scrollbars, --mute-audio, --blink-settings=primaryHov..., --no-sandbox, --ipc=host, --disable-dev-shm-usage, --whitelisted-ips, --remote-debugging-port=0]}}]
chrome_1        | Starting ChromeDriver 97.0.4692.71 (adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}) on port 50957
chrome_1        | Only local connections are allowed.
chrome_1        | Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
chrome_1        | ChromeDriver was started successfully.
chrome_1        | [1643797905.729][SEVERE]: bind() failed: Cannot assign requested address (99)
chrome_1        | 10:31:45.902 INFO [ProtocolHandshake.createSession] - Detected dialect: W3C
selenium-hub    | 10:31:45.913 INFO [LocalDistributor.newSession] - Session created by the distributor. Id: 5851a61174bb24efcecb2c9d0a7e2b2f, Caps: Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 97.0.4692.99, chrome: {chromedriverVersion: 97.0.4692.71 (adefa7837d02a..., userDataDir: /tmp/.com.google.Chrome.U2qBGk}, goog:chromeOptions: {debuggerAddress: localhost:35301}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: linux, proxy: {}, se:cdp: ws://172.18.0.3:4444/sessio..., se:cdpVersion: 97.0.4692.99, se:vnc: ws://172.18.0.3:4444/sessio..., se:vncEnabled: true, se:vncLocalAddress: ws://172.18.0.3:7900, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
selenium-hub    | 10:31:46.081 INFO [LocalSessionMap.lambda$new$0] - Deleted session from local session map, Id: 5851a61174bb24efcecb2c9d0a7e2b2f
```
